/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bowling.approvals;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.stream.Collectors;

public class BowlingGame {
    ArrayList<Integer> rolls = new ArrayList<>();

    public String score() {
        String firstRoll = rolls.size() == 0 ? " " : rolls.get(0).toString();
        return " ____________________________________________________________\n" +
                "|__1__|__2__|__3__|__4__|__5__|__6__|__7__|__8__|__9__|__10__|\n" +
                "| " + firstRoll + " |_|   |_|   |_|   |_|   |_|   |_|   |_|   |_|   |_|  |_|_|\n" +
                "|     |     |     |     |     |     |     |     |     |      |\n" +
                "|_____|_____|_____|_____|_____|_____|_____|_____|_____|______|";
    }

    public void roll(int roll) {
        rolls.add(roll);
    }
}
